/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ApiSuggestionRouteImport } from './routes/api/suggestion'
import { Route as ApiQuickEditRouteImport } from './routes/api/quick-edit'
import { Route as ApiInngestRouteRouteImport } from './routes/api/inngest/route'
import { Route as mainMainLayoutRouteRouteImport } from './routes/(main)/_main-layout/route'
import { Route as authAuthLayoutRouteRouteImport } from './routes/(auth)/_auth-layout/route'
import { Route as mainMainLayoutIndexRouteImport } from './routes/(main)/_main-layout/index'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as authAuthLayoutSignUpRouteImport } from './routes/(auth)/_auth-layout/sign-up'
import { Route as authAuthLayoutSignInRouteImport } from './routes/(auth)/_auth-layout/sign-in'
import { Route as ApiAiChatRouteRouteImport } from './routes/api/ai/chat/route'
import { Route as mainMainLayoutProjectsProjectIdRouteRouteImport } from './routes/(main)/_main-layout/projects.$projectId.route'
import { Route as mainMainLayoutProjectsProjectIdIndexRouteImport } from './routes/(main)/_main-layout/projects.$projectId.index'

const ApiSuggestionRoute = ApiSuggestionRouteImport.update({
  id: '/api/suggestion',
  path: '/api/suggestion',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiQuickEditRoute = ApiQuickEditRouteImport.update({
  id: '/api/quick-edit',
  path: '/api/quick-edit',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiInngestRouteRoute = ApiInngestRouteRouteImport.update({
  id: '/api/inngest',
  path: '/api/inngest',
  getParentRoute: () => rootRouteImport,
} as any)
const mainMainLayoutRouteRoute = mainMainLayoutRouteRouteImport.update({
  id: '/(main)/_main-layout',
  getParentRoute: () => rootRouteImport,
} as any)
const authAuthLayoutRouteRoute = authAuthLayoutRouteRouteImport.update({
  id: '/(auth)/_auth-layout',
  getParentRoute: () => rootRouteImport,
} as any)
const mainMainLayoutIndexRoute = mainMainLayoutIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => mainMainLayoutRouteRoute,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const authAuthLayoutSignUpRoute = authAuthLayoutSignUpRouteImport.update({
  id: '/sign-up',
  path: '/sign-up',
  getParentRoute: () => authAuthLayoutRouteRoute,
} as any)
const authAuthLayoutSignInRoute = authAuthLayoutSignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => authAuthLayoutRouteRoute,
} as any)
const ApiAiChatRouteRoute = ApiAiChatRouteRouteImport.update({
  id: '/api/ai/chat',
  path: '/api/ai/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const mainMainLayoutProjectsProjectIdRouteRoute =
  mainMainLayoutProjectsProjectIdRouteRouteImport.update({
    id: '/projects/$projectId',
    path: '/projects/$projectId',
    getParentRoute: () => mainMainLayoutRouteRoute,
  } as any)
const mainMainLayoutProjectsProjectIdIndexRoute =
  mainMainLayoutProjectsProjectIdIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => mainMainLayoutProjectsProjectIdRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/api/inngest': typeof ApiInngestRouteRoute
  '/api/quick-edit': typeof ApiQuickEditRoute
  '/api/suggestion': typeof ApiSuggestionRoute
  '/api/ai/chat': typeof ApiAiChatRouteRoute
  '/sign-in': typeof authAuthLayoutSignInRoute
  '/sign-up': typeof authAuthLayoutSignUpRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/': typeof mainMainLayoutIndexRoute
  '/projects/$projectId': typeof mainMainLayoutProjectsProjectIdRouteRouteWithChildren
  '/projects/$projectId/': typeof mainMainLayoutProjectsProjectIdIndexRoute
}
export interface FileRoutesByTo {
  '/api/inngest': typeof ApiInngestRouteRoute
  '/api/quick-edit': typeof ApiQuickEditRoute
  '/api/suggestion': typeof ApiSuggestionRoute
  '/api/ai/chat': typeof ApiAiChatRouteRoute
  '/sign-in': typeof authAuthLayoutSignInRoute
  '/sign-up': typeof authAuthLayoutSignUpRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/': typeof mainMainLayoutIndexRoute
  '/projects/$projectId': typeof mainMainLayoutProjectsProjectIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/(auth)/_auth-layout': typeof authAuthLayoutRouteRouteWithChildren
  '/(main)/_main-layout': typeof mainMainLayoutRouteRouteWithChildren
  '/api/inngest': typeof ApiInngestRouteRoute
  '/api/quick-edit': typeof ApiQuickEditRoute
  '/api/suggestion': typeof ApiSuggestionRoute
  '/api/ai/chat': typeof ApiAiChatRouteRoute
  '/(auth)/_auth-layout/sign-in': typeof authAuthLayoutSignInRoute
  '/(auth)/_auth-layout/sign-up': typeof authAuthLayoutSignUpRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/(main)/_main-layout/': typeof mainMainLayoutIndexRoute
  '/(main)/_main-layout/projects/$projectId': typeof mainMainLayoutProjectsProjectIdRouteRouteWithChildren
  '/(main)/_main-layout/projects/$projectId/': typeof mainMainLayoutProjectsProjectIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/api/inngest'
    | '/api/quick-edit'
    | '/api/suggestion'
    | '/api/ai/chat'
    | '/sign-in'
    | '/sign-up'
    | '/api/auth/$'
    | '/'
    | '/projects/$projectId'
    | '/projects/$projectId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/api/inngest'
    | '/api/quick-edit'
    | '/api/suggestion'
    | '/api/ai/chat'
    | '/sign-in'
    | '/sign-up'
    | '/api/auth/$'
    | '/'
    | '/projects/$projectId'
  id:
    | '__root__'
    | '/(auth)/_auth-layout'
    | '/(main)/_main-layout'
    | '/api/inngest'
    | '/api/quick-edit'
    | '/api/suggestion'
    | '/api/ai/chat'
    | '/(auth)/_auth-layout/sign-in'
    | '/(auth)/_auth-layout/sign-up'
    | '/api/auth/$'
    | '/(main)/_main-layout/'
    | '/(main)/_main-layout/projects/$projectId'
    | '/(main)/_main-layout/projects/$projectId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  authAuthLayoutRouteRoute: typeof authAuthLayoutRouteRouteWithChildren
  mainMainLayoutRouteRoute: typeof mainMainLayoutRouteRouteWithChildren
  ApiInngestRouteRoute: typeof ApiInngestRouteRoute
  ApiQuickEditRoute: typeof ApiQuickEditRoute
  ApiSuggestionRoute: typeof ApiSuggestionRoute
  ApiAiChatRouteRoute: typeof ApiAiChatRouteRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/api/suggestion': {
      id: '/api/suggestion'
      path: '/api/suggestion'
      fullPath: '/api/suggestion'
      preLoaderRoute: typeof ApiSuggestionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/quick-edit': {
      id: '/api/quick-edit'
      path: '/api/quick-edit'
      fullPath: '/api/quick-edit'
      preLoaderRoute: typeof ApiQuickEditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/inngest': {
      id: '/api/inngest'
      path: '/api/inngest'
      fullPath: '/api/inngest'
      preLoaderRoute: typeof ApiInngestRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(main)/_main-layout': {
      id: '/(main)/_main-layout'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof mainMainLayoutRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/_auth-layout': {
      id: '/(auth)/_auth-layout'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof authAuthLayoutRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(main)/_main-layout/': {
      id: '/(main)/_main-layout/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof mainMainLayoutIndexRouteImport
      parentRoute: typeof mainMainLayoutRouteRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/_auth-layout/sign-up': {
      id: '/(auth)/_auth-layout/sign-up'
      path: '/sign-up'
      fullPath: '/sign-up'
      preLoaderRoute: typeof authAuthLayoutSignUpRouteImport
      parentRoute: typeof authAuthLayoutRouteRoute
    }
    '/(auth)/_auth-layout/sign-in': {
      id: '/(auth)/_auth-layout/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof authAuthLayoutSignInRouteImport
      parentRoute: typeof authAuthLayoutRouteRoute
    }
    '/api/ai/chat': {
      id: '/api/ai/chat'
      path: '/api/ai/chat'
      fullPath: '/api/ai/chat'
      preLoaderRoute: typeof ApiAiChatRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(main)/_main-layout/projects/$projectId': {
      id: '/(main)/_main-layout/projects/$projectId'
      path: '/projects/$projectId'
      fullPath: '/projects/$projectId'
      preLoaderRoute: typeof mainMainLayoutProjectsProjectIdRouteRouteImport
      parentRoute: typeof mainMainLayoutRouteRoute
    }
    '/(main)/_main-layout/projects/$projectId/': {
      id: '/(main)/_main-layout/projects/$projectId/'
      path: '/'
      fullPath: '/projects/$projectId/'
      preLoaderRoute: typeof mainMainLayoutProjectsProjectIdIndexRouteImport
      parentRoute: typeof mainMainLayoutProjectsProjectIdRouteRoute
    }
  }
}

interface authAuthLayoutRouteRouteChildren {
  authAuthLayoutSignInRoute: typeof authAuthLayoutSignInRoute
  authAuthLayoutSignUpRoute: typeof authAuthLayoutSignUpRoute
}

const authAuthLayoutRouteRouteChildren: authAuthLayoutRouteRouteChildren = {
  authAuthLayoutSignInRoute: authAuthLayoutSignInRoute,
  authAuthLayoutSignUpRoute: authAuthLayoutSignUpRoute,
}

const authAuthLayoutRouteRouteWithChildren =
  authAuthLayoutRouteRoute._addFileChildren(authAuthLayoutRouteRouteChildren)

interface mainMainLayoutProjectsProjectIdRouteRouteChildren {
  mainMainLayoutProjectsProjectIdIndexRoute: typeof mainMainLayoutProjectsProjectIdIndexRoute
}

const mainMainLayoutProjectsProjectIdRouteRouteChildren: mainMainLayoutProjectsProjectIdRouteRouteChildren =
  {
    mainMainLayoutProjectsProjectIdIndexRoute:
      mainMainLayoutProjectsProjectIdIndexRoute,
  }

const mainMainLayoutProjectsProjectIdRouteRouteWithChildren =
  mainMainLayoutProjectsProjectIdRouteRoute._addFileChildren(
    mainMainLayoutProjectsProjectIdRouteRouteChildren,
  )

interface mainMainLayoutRouteRouteChildren {
  mainMainLayoutIndexRoute: typeof mainMainLayoutIndexRoute
  mainMainLayoutProjectsProjectIdRouteRoute: typeof mainMainLayoutProjectsProjectIdRouteRouteWithChildren
}

const mainMainLayoutRouteRouteChildren: mainMainLayoutRouteRouteChildren = {
  mainMainLayoutIndexRoute: mainMainLayoutIndexRoute,
  mainMainLayoutProjectsProjectIdRouteRoute:
    mainMainLayoutProjectsProjectIdRouteRouteWithChildren,
}

const mainMainLayoutRouteRouteWithChildren =
  mainMainLayoutRouteRoute._addFileChildren(mainMainLayoutRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  authAuthLayoutRouteRoute: authAuthLayoutRouteRouteWithChildren,
  mainMainLayoutRouteRoute: mainMainLayoutRouteRouteWithChildren,
  ApiInngestRouteRoute: ApiInngestRouteRoute,
  ApiQuickEditRoute: ApiQuickEditRoute,
  ApiSuggestionRoute: ApiSuggestionRoute,
  ApiAiChatRouteRoute: ApiAiChatRouteRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
